### PR TITLE
Add simple eventbuffer and generate temporal results for #95

### PR DESCRIPTION
**Pull request by ccrock4t**
I added a simple version of event buffer.

This buffer holds first-order events, sorted by time.
        
The purpose of this buffer is to generate temporal implication statements, e.g., (A &/ B =/> C) and compound events, e.g., (A &/ B).

The operation for generating temporal statements is exhaustive.

The oldest events are at the lowest index, the newest events are at the highest index. The larger the event's timestamp, the newer it is.

### CODE REVIEW

**Review by maxeeem — APPROVED** [review]
As you mention in the comments, this will not scale but if the intention is to have _some_ implementation for now and rewrite it later to use Bags then this would be ok.

I'm also not sure about n^3 because if we want to compose 4-component implication such as (&/,A,B,C) =/> D wouldn't this result in n^4 and so on for longer sequences, exploding exponentially?

**Comment by ccrock4t** [comment]
>If we want to compose 4-component implication such as (&/,A,B,C) =/> D wouldn't this result in n^4 and so on for longer sequences?
@maxeeem 

Yep, I agree if we are exhaustively creating all compounds, the time complexity will depend how many components we want to piece together at a time (i.e., how many nested For loops). For now since we only want the most simple version, we will only do the 3 components, which includes the precondition $A$, operation $B$, and postcondition $C$.

To include more components in the compounds, such a 4-component implications, we could explicitly create them (which, as you mentioned would worsen the time complexity). Alternatively, we could try to let NAL implicitly handle them by simplifying expressions. For example, we can consider letting compound events like (&/,A,B) into the EventBuffer. Then the event would fit into a "3-component" implication (&/,(&/,A,B),C =/> D), which simplifies to the 4-component implication (&/,A,B,C =/> D)

**Comment by ccrock4t** [comment]
Sure, I can add them

**Comment by ccrock4t** [comment]
@bowen-xu Some tests are added now, in a new Buffer Test file

**Comment by ccrock4t** [comment]
The flow is like this:

image

**Pull request merged**
