### PR TITLE
added .processed property to Task

### PR DESCRIPTION
**Pull request by maxeeem**
This seems too easy :) I must be missing something.

Is this really all that was required? How to ensure there are no unintended consequences?

### CODE REVIEW

**Comment by ccrock4t** [comment]
Question: Is the task only meant to processed once in this NARS implementation? If so, why return the task to the buffer at all, instead of consuming it?

**Comment by maxeeem** [comment]
> Question: Is the task only meant to processed once in this NARS implementation? If so, why return the task to the buffer at all, instead of consuming it?

@ccrock4t Yeah, I'm not sure... I was going off of the issue description. But now that you mention it, perhaps we need to check the technical report, I vaguely remember there being something about tasks being processed repeatedly, until some threshold in achieving level.

**Comment by bowen-xu** [comment]
@ccrock4t @maxeeem I disscussed this issue with Pei, and Christian is correct. I followed the code of OpenNARS 3.1.0, which was developed by Patrick. There should have been some temporal induction routines in global buffer,  that's why tasks needs to be put back to the buffer. However, such routines haven't been implemented yet. So we can just toss a task after it is processed. The newest design is on event-buffer; that would be a different story.

**Review by bowen-xu — COMMENTED** [review]
looks good.

**Pull request merged**
